export enum FieldPropsEnum {
  key = "key",
  id = "id",
  path = "path",
  name = "name",
  fields = "fields",
  ref= "ref",
  type = "type",
  value = "value",
  initial = "initial",
  default = "default",
  checked = "checked",
  label = "label",
  placeholder = "placeholder",
  error = "error",
  validatedWith = "validatedWith",
  validators = "validators",
  rules = "rules",
  related = "related",
  options = "options",
  extra = "extra",
  bindings = "bindings",
  hooks = "hooks",
  handlers = "handlers",
  input="input",
  output="output",
  interceptors = "interceptors",
  observers = "observers",
  // computed
  disabled = "disabled",
  deleted = "deleted",
  blurred = "blurred",
  clearing = "clearing",
  resetting = "resetting",
  changed = "changed",
  touched = "touched",
  focused = "focused",
  isEmpty = "isEmpty",
  isDefault = "isDefault",
  isPristine = "isPristine",
  isDirty = "isDirty",
  isValid = "isValid",
  hasError = "hasError",
  // handlers
  onInit = "onInit",
  onChange = "onChange",
  onBlur = "onBlur",
  onFocus = "onFocus",
  onToggle = "onToggle",
  onDrop = "onDrop",
  onSubmit = "onSubmit",
  onReset = "onReset",
  onClear = "onClear",
  onAdd = "onAdd",
  onDel = "onDel",
  autoFocus = "autoFocus",
  onKeyDown = "onKeyDown",
  onKeyUp = 'onKeyUp',
}

export type FieldPropsType = {
  [key in FieldPropsEnum]?: any;
}
