name: Mobx React Form
on:
  push:
    branches:
      - master
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mobx: [6, 7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm install --force
      - name: Install MobX ${{ matrix.mobx }}
        run: npm install --no-save --force mobx@${{ matrix.mobx }}
      - run: npm run cover
      - run: npm run coverage:check
      - run: npm run build
      - run: npm run coverage:report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Semantic Release
        if: matrix.mobx == 7
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
